name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install
        run: yarn --no-progress --non-interactive --frozen-lockfile
      - name: Typecheck
        run: yarn typecheck
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test
